### ISSUE TITLE
Speed up export

### ISSUE THREAD

**Issue by d-lord** [smashwilson/slack-emojinator#19]
Hi! Thanks for making this project - I've found it really useful.

[I've implemented a similar export script which is much faster against lots of emoji](https://github.com/d-lord/slackmoji-swarm#profiling). Would you be interested in a pull request to implement this speedup in your project?

emojinator is basically a superset of my project anyway, so I might as well merge in the performance changes and kill mine off.

Mine was written for Python 3.6. What language level are you targeting?

**Comment by smashwilson** [comment]
Ooh, aio! Fancy.

> Would you be interested in a pull request to implement this speedup in your project?

Definitely, that sounds awesome :+1:

> Mine was written for Python 3.6. What language level are you targeting?

I'd originally targeted 2.7 and 3.x cross-compatibility, since the script was initially a hundred lines or so and that was simple. I'm fine with bumping it to 3.6 only as long as you add a note to the README about it and here are compatible versions of the dependencies.

Idle thought: it might be even nicer to package this as a Docker container - then we could lock to whatever version of Python we like.

**Comment by smashwilson** [comment]
> emojinator is basically a superset of my project anyway, so I might as well merge in the performance changes and kill mine off.

Sure, if you like :smile: I've invited you to be a collaborator on this project too.

**Comment by kvarga** [comment]
Docker seems overkill. Virtualenv's can handle running multiple Python
versions fine IMO.

--
Kyle Varga

**Comment by d-lord** [comment]
Great, I'll bring in the changes on a branch for review. ✌️

**Comment by d-lord** [comment]
First version is now on the `aiohttp` branch. I need to go through and tidy the code up, but how does it look so far?

Particularly keen for your thoughts on:
- logging
- having to decouple `export.py` from `upload.py`'s `_session` method

Quick profiling on my main team showed 1161 emoji in 28s with this version, vs 3m24s for the current master.

**Comment by d-lord** [comment]
Hey @smashwilson, I'm thinking of merging this to master. Any input before I do?
